name: C Code Formatting on Push

on: [push]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run clang-format in Kernel and Userland
        run: |
          find Kernel Userland -name '*.c' -o -name '*.h' | xargs clang-format -i
      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "style: format C code with clang-format"
          add: "Kernel/*.c Kernel/*.h Userland/*.c Userland/*.h"